### ISSUE TITLE
Not connecting to peers

### ISSUE THREAD

**Issue by c3piio** [chronokings/huntercore#5]
The HunterCore Win64 0.16 wallet should connect to peers

The HunterCore Win64 0.16 wallet doesn't connect to peers

I launch the QT wallet. It is stuck on connecting to peers.

Included in HunterCore Win64 0.16.0

Windows 10 64 bit, Core i5 2520M 2.5 ghz, , SSD

**Comment by xaya** [comment]
Hi. 
afaik there are no hard coded nodes in the Huntercoin clients - or dnsseeds configured.

You should be able to connect to the other peers if you add these nodes - you can put them in the conf file or you can add them with huntercoin-cli or in the qt console

addnode=167.99.154.94
addnode=178.128.228.101
addnode=139.59.42.96
addnode=46.101.15.140
addnode=82.200.205.30
addnode=144.76.222.140
